# Quest definitions (v2, 50 quests). Single source for data/quests.json, data/quests.csv and the tables in quests.md.
# Edit here, then run build_quests.py.
# Step tuple: (event, objective, where, note)
#   event = world-graph arrival outcome: quest_offer | nothing | miniboss | item | portal | story | treasure,
#           plus 2 non-node kinds: edge_battle (fights on edges) and boss (a zone's boss node)
#   where = realm 1: {"graph","node"} (real ids). Realms 2-9: {"zone","nodeKind","position"}
#           (+ "ref" = node in the current generated reference layout, informative only)

def W1(node): return {"graph": "realm_1", "node": node}
def Z(zone, kind, pos, ref=None):
    d = {"zone": zone, "nodeKind": kind, "position": pos}
    if ref: d["ref"] = ref
    return d

Q = []
def q(**kw): Q.append(kw)

# ---------------- Realm 1 Starter Meadow (G=6) ----------------
q(id="q1_bounty", realm=1, zone="meadow", type="slay", story="side",
  title=("赶走角兔", "Rabbits in the Cabbages"), giver="farmer_li", giverAt=W1("m_farm"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "farmer_li"}, W1("m_farm"), "Farmer Li's cabbages are being nibbled (existing event m_farm.2)."),
         ("edge_battle", {"type": "kill", "enemy": "horned_rabbit", "n": 8, "scope": {"realm": 1}}, {"graph": "realm_1", "edges": ["e2", "e3", "e4", "e5", "e6"]}, "Any fight in realm 1 counts."),
         ("quest_offer", {"type": "turn_in", "npc": "farmer_li"}, W1("m_farm"), "Return to Farmer Li.")],
  rewards=dict(G=8, items={"honey": 1}, L=15),
  words=["C001", "C007", "C039", "C038", "C011"],
  summary="Chase 8 horned rabbits away from Farmer Li's cabbage field, then tell him they're gone.")
q(id="q1_hoe", realm=1, zone="meadow", type="find", story="side",
  title=("找回锄头", "The Lost Hoe"), giver="farmer_li", giverAt=W1("m_farm"), hook="q1_hoe",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "farmer_li"}, W1("m_farm"), "Li: 'My hoe! Where did it go?' (existing event m_farm.1)"),
         ("story", {"type": "reach", "node": "m_well"}, W1("m_well"), "Existing story event well_hint (m_well.3)."),
         ("item", {"type": "pickup", "item": "farmers_hoe"}, W1("m_well"), "Existing event m_well.1 (cond questActive q1_hoe)."),
         ("quest_offer", {"type": "turn_in", "npc": "farmer_li"}, W1("m_farm"), "Existing story farmer_thanks (m_farm.3).")],
  rewards=dict(G=7, items={"honey": 1}, L=10),
  words=["C035", "C037", "C594", "C595", "C007"],
  summary="Farmer Li dropped his hoe somewhere; spot the glint in the old well and bring it back.")
q(id="q1_carrot", realm=1, zone="warren", type="fetch", story="side",
  title=("金萝卜", "The Golden Carrot Thief"), giver="xiaoming", giverAt=W1("w_path"), hook="q1_carrot",
  turnIn={"npc": "xiaoming", "graph": "realm_1", "node": "village"}, requires={"bossDefeated": "clover_hills"},
  steps=[("quest_offer", {"type": "talk", "npc": "xiaoming"}, W1("w_path"), "Xiaoming: '救命! A rabbit took my golden carrot!' (existing event w_path.1)"),
         ("miniboss", {"type": "fight", "node": "w_nest", "enemies": ["swift_horned_rabbit", "wolf_pup"]}, W1("w_nest"), "Existing event w_nest.1 (thief mini-boss)."),
         ("item", {"type": "pickup", "item": "golden_carrot"}, W1("w_lake"), "The thief hid it by Clover Lake: existing event w_lake.1."),
         ("quest_offer", {"type": "turn_in", "npc": "xiaoming"}, W1("village"), "Xiaoming waits at home in Little Hill Village (hook turnIn).")],
  rewards=dict(G=15, items={"feather": 1}, L=20),
  words=["C076", "C077", "C078", "C282", "C090", "C092"],
  summary="Beat the speedy thief rabbit in its nest, find the golden carrot by Clover Lake and take it home to Xiaoming.")

# ---------------- Realm 2 Honeycomb Forest (G=12) ----------------
q(id="q2_lost_panda", realm=2, zone="forest", type="find", story="side",
  title=("找熊猫", "Duoduo's Lost Panda"), giver="duoduo", giverAt=Z("forest", "town", "entry_town"), hook=None,
  turnIn="giver", requires={"bossDefeated": "forest"},
  steps=[("quest_offer", {"type": "talk", "npc": "duoduo"}, Z("forest", "town", "entry_town"), "Duoduo (6) lost her toy panda picking flowers in the woods (Jack's 'lost item in the woods')."),
         ("story", {"type": "reach"}, Z("forest", "waypoint", "mid_zone"), "Xiaolong spots a trail of paw-print stickers."),
         ("item", {"type": "pickup", "item": "toy_panda"}, Z("forest", "chest", "dead_end"), "Up a hollow tree at a dead end (quest item fires before the chest)."),
         ("quest_offer", {"type": "turn_in", "npc": "duoduo"}, Z("forest", "town", "entry_town"), "Duoduo hugs it: 谢谢!")],
  rewards=dict(G=9, items={"honey": 1}, L=10),
  words=["C155", "C145", "C143", "C142", "C454", "C007"],
  summary="Follow the sticker trail through the Flower Glade to find Duoduo's toy panda and bring it home.")
q(id="q2_spider_silk", realm=2, zone="forest", type="fetch", story="side",
  title=("收集蜘蛛丝", "Silk for the Bee Veils"), giver="granny_mi", giverAt=Z("forest", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None, alsoOnBoard=True,
  steps=[("quest_offer", {"type": "talk", "npc": "granny_mi"}, Z("forest", "town", "entry_town"), "The beekeeper's veils are torn; the bees are cranky."),
         ("edge_battle", {"type": "collect", "item": "spider_silk", "n": 5, "dropFrom": ["forest_spider"], "dropChance": 0.35}, Z("forest", "path", "any"), "Drops from Forest Spiders."),
         ("quest_offer", {"type": "turn_in", "npc": "granny_mi"}, Z("forest", "town", "entry_town"), "Granny Mi sews new veils.")],
  rewards=dict(G=11, items={"honey": 2}, L=15),
  words=["C115", "C122", "C119", "C118", "C121"],
  summary="Collect 5 strands of spider silk so Granny Mi can mend her bee veils.")
q(id="q2_bubble_lesson", realm=2, zone="forest", type="fetch", story="main",
  title=("白奶奶的泡泡课", "Granny Bai's Bubble Lesson"), giver="granny_bai", giverAt=Z("forest", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "granny_bai"}, Z("forest", "town", "entry_town"), "Granny Bai 'happens to be in town' and offers a first spell lesson."),
         ("item", {"type": "pickup", "item": "soap_flower", "n": 3}, Z("forest", "waypoint", "branch"), "3 soap-flowers on side branches (quest items)."),
         ("quest_offer", {"type": "words", "pool": "L2.1", "n": 8, "countFrom": "accept"}, Z("forest", "town", "entry_town"), "Get 8 Flower Glade words Ready (battle or practice)."),
         ("quest_offer", {"type": "turn_in", "npc": "granny_bai"}, Z("forest", "town", "entry_town"), "She teaches 泡泡术; Honey Town's shelf shows 'Granny Bai's lesson' instead of a price.")],
  rewards=dict(G=0, items={}, L=15, spells=["bubble_spell"]),
  words=["C093", "C094", "C107", "C119", "C642"],
  summary="Gather 3 soap-flowers and learn 8 forest words; Granny Bai teaches you your first spell, Bubble Spell.")
q(id="q2_royal_jelly", realm=2, zone="great_hive", type="fetch", story="main",
  title=("蜂后的蜂王浆", "The Queen's Stolen Jelly"), giver="yezi", giverAt=Z("great_hive", "npc", "level_1_mid", "great_hive_1/npc_1"), hook="q2_great_hive_1_npc_1",
  turnIn="giver", requires={"bossDefeated": "forest"},
  steps=[("quest_offer", {"type": "talk", "npc": "yezi"}, Z("great_hive", "npc", "level_1_mid", "great_hive_1/npc_1"), "Yezi the elf: the bees blame Honey Town for a theft."),
         ("miniboss", {"type": "fight", "enemies": ["royal_guard_bee", "giant_bee"]}, Z("great_hive", "miniboss", "dead_end", "great_hive_1/miniboss_1"), "Guards around Pipi's stash."),
         ("story", {"type": "pickup", "item": "royal_jelly"}, Z("great_hive", "story", "dead_end", "great_hive_1/story_1"), "Pipi's stash: the jar and a red feather. First proof it was Pipi."),
         ("boss", {"type": "boss", "zone": "great_hive"}, Z("great_hive", "boss", "boss_room"), "After the Queen's battle, give the jelly back (clear scene)."),
         ("quest_offer", {"type": "turn_in", "npc": "yezi"}, Z("great_hive", "npc", "level_1_mid", "great_hive_1/npc_1"), "Yezi teaches Heal (spec: Honeycomb quest).")],
  rewards=dict(G=10, items={"manatea": 1}, L=25, skills=["heal"]),
  words=["C130", "C134", "C138", "C135", "C342", "C343"],
  summary="Find the royal jelly Pipi stole, return it to the Queen Bee, and Yezi teaches you Heal.")

# ---------------- Realm 3 Crossroads Market (G=18) ----------------
q(id="q3_rescue_fei", realm=3, zone="crossroads_highway", type="rescue", story="main",
  title=("救小飞", "Fei and the Bandit Cave"), giver="xiaomei", giverAt=Z("crossroads_highway", "village", "outpost"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "xiaomei"}, Z("crossroads_highway", "village", "outpost"), "Fei's little sister: bandits took him (Jack's 'rescue a friend from bandits in a cave')."),
         ("story", {"type": "reach"}, Z("crossroads_highway", "story", "mid_zone", "realm_3/story_1"), "Fei's wooden sword and a ransom note: 一共多少钱?"),
         ("miniboss", {"type": "fight", "enemies": ["road_bandit", "road_bandit", "road_bandit"]}, Z("crossroads_highway", "miniboss", "dead_end", "realm_3/miniboss_1"), "The Sack Brothers in their cave."),
         ("story", {"type": "talk", "npc": "fei"}, Z("crossroads_highway", "miniboss", "dead_end", "realm_3/miniboss_1"), "Untie Fei (scene after the clear)."),
         ("quest_offer", {"type": "turn_in", "npc": "xiaomei"}, Z("crossroads_highway", "village", "outpost"), "Reunion; Fei grumbles 谢谢.")],
  rewards=dict(G=5, items={}, gear=[(3, "shield", "fine")], L=25),
  words=["C166", "C663", "C164", "C668", "C076", "C282"],
  summary="Follow the ransom note to the bandits' cave, beat the Sack Brothers and bring Fei home to his sister.")
q(id="q3_stolen_hats", realm=3, zone="crossroads_highway", type="fetch", story="side",
  title=("找帽子", "Hats Off!"), giver="auntie_hat", giverAt=Z("crossroads_highway", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None, alsoOnBoard=True,
  steps=[("quest_offer", {"type": "talk", "npc": "auntie_hat"}, Z("crossroads_highway", "town", "entry_town"), "The hat seller's stock was stolen by bandits wearing it all at once."),
         ("edge_battle", {"type": "collect", "item": "stolen_hat", "n": 5, "dropFrom": ["road_bandit"], "dropChance": 0.35}, Z("crossroads_highway", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "auntie_hat"}, Z("crossroads_highway", "town", "entry_town"), "")],
  rewards=dict(G=6, items={"honey": 1}, L=15),
  words=["C162", "C163", "C171", "C172", "C190"],
  summary="Knock 5 stolen hats off the road bandits' heads and return them to the hat stall.")
q(id="q3_caravan", realm=3, zone="crossroads_highway", type="escort", story="side",
  title=("护送马车", "The Toy Caravan"), giver="boss_qian", giverAt=Z("crossroads_highway", "town", "entry_town"), hook=None,
  turnIn={"npc": "boss_qian", "zone": "crossroads_highway", "nodeKind": "village"}, requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "boss_qian"}, Z("crossroads_highway", "town", "entry_town"), "Boss Qian's toy cart must reach the outpost."),
         ("edge_battle", {"type": "escort", "npc": "donkey_cart", "to": {"zone": "crossroads_highway", "nodeKind": "village"}}, Z("crossroads_highway", "path", "town_to_outpost"), "The cart follows; fights on the way as normal."),
         ("story", {"type": "reach"}, Z("crossroads_highway", "story", "mid_zone", "realm_3/story_2"), "A cheeky toll-goblin wants money: 太贵了! / 便宜一点儿吧 (choice)."),
         ("quest_offer", {"type": "deliver", "item": "toy_crate", "to": "boss_qian"}, Z("crossroads_highway", "village", "outpost"), "Qian meets you at the outpost.")],
  rewards=dict(G=6, items={"feather": 1}, L=15),
  words=["C167", "C168", "C169", "C170", "C679", "C663"],
  summary="Walk Boss Qian's toy cart down the highway to the outpost, haggling a cheeky toll-goblin down on the way.")
q(id="q3_lost_wallet", realm=3, zone="night_bazaar", type="find", story="side",
  title=("钱包不见了", "The Wallet in the Cellar"), giver="grandpa_lantern", giverAt=Z("night_bazaar", "npc", "level_1_mid", "bazaar_cellars_1/npc_1"), hook="q3_bazaar_cellars_1_npc_1",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "grandpa_lantern"}, Z("night_bazaar", "npc", "level_1_mid", "bazaar_cellars_1/npc_1"), "An old lantern seller dropped his wallet down here."),
         ("treasure", {"type": "reach"}, Z("night_bazaar", "chest", "dead_end"), "Decoy: a normal chest, but no wallet. 'Not this one!'"),
         ("miniboss", {"type": "fight", "enemies": ["mimic", "slime"]}, Z("night_bazaar", "miniboss", "dead_end", "bazaar_cellars_1/miniboss_1"), "A mimic swallowed the wallet."),
         ("item", {"type": "pickup", "item": "red_wallet"}, Z("night_bazaar", "miniboss", "dead_end", "bazaar_cellars_1/miniboss_1"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "grandpa_lantern"}, Z("night_bazaar", "npc", "level_1_mid", "bazaar_cellars_1/npc_1"), "")],
  rewards=dict(G=8, items={"honey": 1}, L=20),
  words=["C668", "C191", "C205", "C206", "C693", "C703"],
  summary="Track the old lantern seller's red wallet to the mimic that swallowed it, and give it back.")
q(id="q3_slime_rainbow", realm=3, zone="night_bazaar", type="slay", story="side",
  title=("彩虹史莱姆", "Slime Rainbow"), giver="dye_maker_lan", giverAt=Z("crossroads_highway", "town", "entry_town"), hook=None,
  turnIn="giver", requires={"bossDefeated": "crossroads_highway"}, alsoOnBoard=True,
  steps=[("quest_offer", {"type": "talk", "npc": "dye_maker_lan"}, Z("crossroads_highway", "town", "entry_town"), "The dye-maker's stall is in Crossroads Market (the night_bazaar overworld has no village; the bazaar itself is the bazaar_cellars dungeon). Offered after the crossroads_highway boss. She needs jelly in four colors."),
         ("edge_battle", {"type": "kill", "enemy": "slime", "n": 4, "variants": ["red", "yellow", "blue", "green"], "scope": {"realm": 3}}, Z("night_bazaar", "path", "any"), "One of each color (the slime shouts its color)."),
         ("quest_offer", {"type": "turn_in", "npc": "dye_maker_lan"}, Z("crossroads_highway", "town", "entry_town"), "")],
  rewards=dict(G=5, items={}, L=15),
  words=["C191", "C192", "C193", "C194", "C197", "C198"],
  summary="Defeat a red, a yellow, a blue and a green slime so the dye-maker can paint the market.")

# ---------------- Realm 4 Goblin Caves (G=27) ----------------
q(id="q4_lost_schoolbag", realm=4, zone="cave_mouth", type="find", story="side",
  title=("书包在哪儿", "Xiaohu's Schoolbag"), giver="xiaohu", giverAt=Z("cave_mouth", "village", "outpost"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "xiaohu"}, Z("cave_mouth", "village", "outpost"), "He escaped the goblins, but his schoolbag didn't."),
         ("portal", {"type": "reach"}, Z("cave_mouth", "portal", "overworld", "realm_4/portal_1"), "Enter Goblin Caves L1."),
         ("item", {"type": "pickup", "item": "schoolbag"}, Z("cave_mouth", "chest", "dead_end"), "Under a pile of bat-chewed pencils."),
         ("quest_offer", {"type": "turn_in", "npc": "xiaohu"}, Z("cave_mouth", "village", "outpost"), "")],
  rewards=dict(G=7, items={"honey": 1}, L=15),
  words=["C229", "C226", "C227", "C228", "C281"],
  summary="Find Xiaohu's schoolbag in the Cave Mouth and bring it back to the miners' camp.")
q(id="q4_glow_moss", realm=4, zone="cave_mouth", type="fetch", story="side",
  title=("石大叔的灯", "Uncle Shi's Lamps"), giver="uncle_shi", giverAt=Z("cave_mouth", "npc", "level_1_mid", "goblin_caves_1/npc_1"), hook="q4_goblin_caves_1_npc_1",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "uncle_shi"}, Z("cave_mouth", "npc", "level_1_mid", "goblin_caves_1/npc_1"), "The dwarf foreman's lamps went out; bats love the dark."),
         ("edge_battle", {"type": "collect", "item": "glow_moss", "n": 5, "dropFrom": ["cave_bat"], "dropChance": 0.35}, Z("cave_mouth", "path", "any"), "Glow-moss clings to cave bats."),
         ("quest_offer", {"type": "turn_in", "npc": "uncle_shi"}, Z("cave_mouth", "npc", "level_1_mid", "goblin_caves_1/npc_1"), "")],
  rewards=dict(G=9, items={"honey": 1}, L=15),
  words=["C286", "C281", "C718", "C222"],
  summary="Collect 5 clumps of glow-moss from cave bats so Uncle Shi's dwarves can light the mine again.")
q(id="q4_free_classmates", realm=4, zone="crystal_tunnels", type="rescue", story="main",
  title=("救同学", "Three Kids in the Crystal Tunnels"), giver="teacher_zhang", giverAt=Z("crystal_tunnels", "story", "level_2_start", "goblin_caves_2/story_1"), hook=None,
  turnIn={"npc": "uncle_shi", "zone": "cave_mouth", "nodeKind": "village"}, requires={"bossDefeated": "cave_mouth"},
  steps=[("story", {"type": "pickup", "item": "paper_plane_note"}, Z("crystal_tunnels", "story", "level_2_start", "goblin_caves_2/story_1"), "A paper-plane note from Teacher Zhang (the offer): three kids are hidden in the tunnels."),
         ("story", {"type": "talk", "npc": "kid_a"}, Z("crystal_tunnels", "story", "branch"), "Kid 1 locked in a crystal cupboard."),
         ("miniboss", {"type": "fight", "enemies": ["goblin_brute", "goblin"]}, Z("crystal_tunnels", "miniboss", "dead_end", "goblin_caves_2/miniboss_1"), "Kid 2 guarded by a brute 'on detention duty'."),
         ("story", {"type": "talk", "npc": "kid_b"}, Z("crystal_tunnels", "miniboss", "dead_end", "goblin_caves_2/deadend_1"), "Kid 3 behind a door that opens for 请 + 谢谢."),
         ("quest_offer", {"type": "turn_in", "npc": "uncle_shi"}, Z("cave_mouth", "village", "outpost"), "The kids run home; parents cheer.")],
  rewards=dict(G=4, items={}, gear=[(4, "shield", "fine")], L=25),
  words=["C224", "C223", "C222", "C253", "C255", "C740"],
  summary="Use Teacher Zhang's paper-plane note to find three classmates hidden in the Crystal Tunnels and send them home.")
q(id="q4_homework", realm=4, zone="goblin_school", type="slay", story="side",
  title=("作业回来了", "Homework Rescue"), giver="teacher_zhang", giverAt=Z("goblin_school", "story", "level_3_classroom", "goblin_caves_3/story_1"), hook=None,
  turnIn="giver", requires={"bossDefeated": "goblin_school"},
  steps=[("quest_offer", {"type": "talk", "npc": "teacher_zhang"}, Z("goblin_school", "story", "level_3_classroom", "goblin_caves_3/story_1"), "After the Headmaster falls, the hall monitors still hoard the class's homework."),
         ("edge_battle", {"type": "kill", "enemy": "goblin_monitor", "n": 6, "scope": {"zone": "goblin_school"}}, Z("goblin_school", "path", "any"), "They hand pages back when beaten."),
         ("quest_offer", {"type": "turn_in", "npc": "teacher_zhang"}, Z("goblin_school", "story", "level_3_classroom"), "")],
  rewards=dict(G=5, items={"honey": 1}, L=15),
  words=["C233", "C234", "C763", "C261", "C262", "C271"],
  summary="Beat 6 goblin hall monitors to win back the class's homework for Teacher Zhang.")
q(id="q4_school_bell", realm=4, zone="goblin_school", type="deliver", story="main",
  title=("新学校的钟", "A Bell for a Real School"), giver="uncle_shi", giverAt=Z("cave_mouth", "village", "outpost"), hook=None,
  turnIn={"npc": "teacher_zhang", "zone": "goblin_school", "nodeKind": "story"}, requires={"bossDefeated": "goblin_school"},
  steps=[("quest_offer", {"type": "talk", "npc": "uncle_shi"}, Z("cave_mouth", "village", "outpost"), "The dwarves forged a school bell so goblins can have a real school."),
         ("portal", {"type": "reach"}, Z("cave_mouth", "portal", "overworld", "realm_4/portal_1"), "Back into the caves (inn warp allowed)."),
         ("quest_offer", {"type": "deliver", "item": "school_bell", "to": "teacher_zhang"}, Z("goblin_school", "story", "level_3_classroom"), "Goblins line up for their first real lesson: 老师好!")],
  rewards=dict(G=5, items={"feather": 1}, L=20),
  words=["C221", "C248", "C231", "C232", "C239", "C292"],
  summary="Carry the dwarves' new bell down to Teacher Zhang, who is opening a real school for the goblins.")

# ---------------- Realm 5 Hydra Swamp (G=36) ----------------
q(id="q5_invitations", realm=5, zone="misty_marsh", type="deliver", story="side",
  title=("生日请帖", "Grandpa Turtle's Birthday Invitations"), giver="grandpa_turtle", giverAt=Z("misty_marsh", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "grandpa_turtle"}, Z("misty_marsh", "town", "entry_town"), "His 1,000th birthday! Three invitations to hand out."),
         ("quest_offer", {"type": "deliver", "item": "invitation", "to": "ferry_auntie"}, Z("misty_marsh", "village", "outpost"), ""),
         ("quest_offer", {"type": "deliver", "item": "invitation", "to": "xiaohe_grandma"}, Z("misty_marsh", "village", "outpost"), ""),
         ("quest_offer", {"type": "deliver", "item": "invitation", "to": "old_fisher"}, Z("hydra_s_lair", "npc", "level_1_entry", "hydra_lair_1/npc_1"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "grandpa_turtle"}, Z("misty_marsh", "town", "entry_town"), "Party scene with cake.")],
  rewards=dict(G=6, items={"bighoney": 1}, L=20),
  words=["C322", "C308", "C309", "C310", "C311", "C325"],
  summary="Hand Grandpa Turtle's birthday invitations to three friends around the swamp and come back for cake.")
q(id="q5_muddy_road", realm=5, zone="misty_marsh", type="slay", story="side",
  title=("别迟到", "Mud on the School Road"), giver="ferry_auntie", giverAt=Z("misty_marsh", "village", "outpost"), hook=None,
  turnIn="giver", requires=None, alsoOnBoard=True,
  steps=[("quest_offer", {"type": "talk", "npc": "ferry_auntie"}, Z("misty_marsh", "village", "outpost"), "Bog monsters make the village kids 迟到 every morning."),
         ("edge_battle", {"type": "kill", "enemy": "bog_monster", "n": 8, "scope": {"realm": 5}}, Z("misty_marsh", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "ferry_auntie"}, Z("misty_marsh", "village", "outpost"), "")],
  rewards=dict(G=6, items={}, L=15),
  words=["C781", "C782", "C304", "C313", "C323"],
  summary="Clear 8 bog monsters off the morning road so the swamp kids stop being late for school.")
q(id="q5_escort_xiaohe", realm=5, zone="misty_marsh", type="escort", story="side",
  title=("送小荷回家", "Xiaohe in the Mist"), giver="xiaohe", giverAt=Z("misty_marsh", "npc", "branch", "realm_5/npc_1"), hook="q5_realm_5_npc_1",
  turnIn={"npc": "xiaohe_grandma", "zone": "misty_marsh", "nodeKind": "village"}, requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "xiaohe"}, Z("misty_marsh", "npc", "branch", "realm_5/npc_1"), "A girl followed a wisp's light and got lost."),
         ("edge_battle", {"type": "escort", "npc": "xiaohe", "to": {"zone": "misty_marsh", "nodeKind": "village"}}, Z("misty_marsh", "path", "npc_to_outpost"), "She follows you and hides during fights."),
         ("story", {"type": "reach"}, Z("misty_marsh", "story", "mid_zone"), "She wants to follow the wisp again: 一会儿 / 现在 (choice)."),
         ("quest_offer", {"type": "turn_in", "npc": "xiaohe_grandma"}, Z("misty_marsh", "village", "outpost"), "Grandma rewards you.")],
  rewards=dict(G=6, items={"honey": 1}, L=15),
  words=["C320", "C303", "C318", "C319", "C784", "C307"],
  summary="Walk little Xiaohe safely through the fog to her grandma's house at the outpost.")
q(id="q5_pocket_watches", realm=5, zone="hydra_s_lair", type="fetch", story="side",
  title=("怀表", "Tick-Tock Lizards"), giver="grandpa_turtle", giverAt=Z("misty_marsh", "town", "entry_town"), hook=None,
  turnIn="giver", requires={"bossDefeated": "misty_marsh"},
  steps=[("quest_offer", {"type": "talk", "npc": "grandpa_turtle"}, Z("misty_marsh", "town", "entry_town"), "Bog lizards stole the town clock's spare watches."),
         ("edge_battle", {"type": "collect", "item": "pocket_watch", "n": 5, "dropFrom": ["bog_lizard"], "dropChance": 0.35}, Z("hydra_s_lair", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "grandpa_turtle"}, Z("misty_marsh", "town", "entry_town"), "")],
  rewards=dict(G=6, items={}, L=15),
  words=["C314", "C315", "C317", "C777", "C326"],
  summary="Take back 5 pocket watches from the bog lizards so Grandpa Turtle can fix the town clock.")
q(id="q5_lost_fishers", realm=5, zone="hydra_s_lair", type="rescue", story="side",
  title=("迷路的渔夫", "Two Sons in the Lair"), giver="old_fisher", giverAt=Z("hydra_s_lair", "npc", "level_1_entry", "hydra_lair_1/npc_1"), hook="q5_hydra_lair_1_npc_1",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "old_fisher"}, Z("hydra_s_lair", "npc", "level_1_entry", "hydra_lair_1/npc_1"), "His two sons went deeper and haven't come back."),
         ("story", {"type": "talk", "npc": "fisher_son_1"}, Z("hydra_s_lair", "npc", "level_1_dead_end", "hydra_lair_1/npc_2"), "Hiding behind roots."),
         ("story", {"type": "talk", "npc": "fisher_son_2"}, Z("hydra_s_lair", "npc", "level_1_deep", "hydra_lair_1/npc_3"), "Stuck on an island; Xiaolong makes a reed bridge."),
         ("miniboss", {"type": "fight", "enemies": ["swamp_wisp", "bog_lizard"]}, Z("hydra_s_lair", "miniboss", "level_1", "hydra_lair_1/miniboss_1"), "The wisp that lured them."),
         ("quest_offer", {"type": "turn_in", "npc": "old_fisher"}, Z("hydra_s_lair", "npc", "level_1_entry"), "")],
  rewards=dict(G=6, items={"honey": 1}, L=25),
  words=["C799", "C315", "C316", "C785", "C786"],
  summary="Find the old fisher's two sons deep in the Hydra's Lair, chase off the wisp that lured them, and report back.")
q(id="q5_fog_bottle", realm=5, zone="hydra_s_lair", type="slay", story="main",
  title=("雾瓶", "Madame Mist's Fog Bottle"), giver="grandpa_turtle", giverAt=Z("misty_marsh", "town", "entry_town"), hook=None,
  turnIn="giver", requires={"flag": "met_madame_mist"},
  steps=[("quest_offer", {"type": "talk", "npc": "grandpa_turtle"}, Z("misty_marsh", "town", "entry_town"), "After meeting Madame Mist: 'Her fog comes from a bottle. Break it!'"),
         ("portal", {"type": "reach"}, Z("hydra_s_lair", "portal", "overworld", "realm_5/portal_1"), ""),
         ("miniboss", {"type": "fight", "enemies": ["swamp_wisp", "bog_monster", "bog_lizard"]}, Z("hydra_s_lair", "miniboss", "level_2", "hydra_lair_2/miniboss_1"), "Guardians of the bottle."),
         ("item", {"type": "pickup", "item": "fog_bottle"}, Z("hydra_s_lair", "miniboss", "level_2"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "grandpa_turtle"}, Z("misty_marsh", "town", "entry_town"), "He seals it and gives you his old shell shield.")],
  rewards=dict(G=0, items={}, gear=[(5, "shield", "heroic")], L=30),
  words=["C539", "C821", "C820", "C542", "C324"],
  summary="Beat the guardians of Madame Mist's fog bottle on the Lair's lower level and bring it to Grandpa Turtle to seal.")

# ---------------- Realm 6 Zombie Lands (G=45) ----------------
q(id="q6_medicine_herbs", realm=6, zone="gloomy_village", type="fetch", story="main",
  title=("找草药", "Herbs for Dr. An"), giver="dr_an", giverAt=Z("gloomy_village", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "dr_an"}, Z("gloomy_village", "town", "entry_town"), "Dawn Chapel is out of medicine."),
         ("item", {"type": "pickup", "item": "sun_herb", "n": 3}, Z("gloomy_village", "chest", "dead_end"), "3 herb patches at dead ends (quest item before the chest)."),
         ("story", {"type": "reach"}, Z("gloomy_village", "story", "mid_zone", "realm_6/story_1"), "Xiaolong sniffs one and sneezes."),
         ("quest_offer", {"type": "turn_in", "npc": "dr_an"}, Z("gloomy_village", "town", "entry_town"), "")],
  rewards=dict(G=8, items={}, L=20),
  words=["C400", "C399", "C398", "C402", "C366", "C383"],
  summary="Gather 3 sun-herbs from the foggy village's corners so Dr. An can brew medicine.")
q(id="q6_hot_soup", realm=6, zone="gloomy_village", type="deliver", story="side",
  title=("送热汤", "Hot Soup Rounds"), giver="cook_ma", giverAt=Z("gloomy_village", "village", "outpost_1"), hook=None,
  turnIn="giver", requires={"bossDefeated": "gloomy_village"},
  steps=[("quest_offer", {"type": "talk", "npc": "cook_ma"}, Z("gloomy_village", "village", "outpost_1"), "Cured villagers are weak; soup helps."),
         ("quest_offer", {"type": "deliver", "item": "soup", "to": "villager_a"}, Z("gloomy_village", "npc", "branch", "realm_6/npc_1"), "你怎么了? / 我头疼"),
         ("quest_offer", {"type": "deliver", "item": "soup", "to": "villager_b"}, Z("gloomy_village", "village", "outpost_1", "realm_6/town_2"), "你没事吧? / 没事"),
         ("quest_offer", {"type": "deliver", "item": "soup", "to": "mayor_liu"}, Z("gloomy_village", "village", "outpost_2"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "cook_ma"}, Z("gloomy_village", "village", "outpost_1"), "")],
  rewards=dict(G=5, items={"honey": 1}, L=15),
  words=["C635", "C386", "C385", "C403", "C384", "C358"],
  summary="Carry Cook Ma's hot soup to three recovering villagers and ask how they feel.")
q(id="q6_old_mine", realm=6, zone="gloomy_village", type="rescue", story="side",
  title=("老矿井", "Trapped in the Old Mine"), giver="miner_gao", giverAt=Z("gloomy_village", "npc", "optional_dungeon", "old_mine_1/npc_1"), hook="q6_old_mine_1_npc_1",
  turnIn="giver", requires=None,
  steps=[("portal", {"type": "reach"}, Z("gloomy_village", "portal", "optional", "realm_6/portal_2"), "Old Mine (optional)."),
         ("quest_offer", {"type": "talk", "npc": "miner_gao"}, Z("gloomy_village", "npc", "optional_dungeon", "old_mine_1/npc_1"), "Two miners are stuck behind sick, grumpy zombies."),
         ("miniboss", {"type": "fight", "enemies": ["zombie", "zombie", "zombie_knight"]}, Z("gloomy_village", "miniboss", "dead_end", "old_mine_1/deadend_1"), "Cured on defeat."),
         ("story", {"type": "reach"}, Z("gloomy_village", "story", "dead_end", "old_mine_1/story_2"), "The miners: 我很害怕 → 别怕."),
         ("quest_offer", {"type": "turn_in", "npc": "miner_gao"}, Z("gloomy_village", "npc", "optional_dungeon"), "")],
  rewards=dict(G=7, items={"honey": 1}, L=25),
  words=["C362", "C378", "C381", "C361", "C401", "C406"],
  summary="Cure the zombies blocking the Old Mine tunnel and lead two scared miners out.")
q(id="q6_lost_dog", realm=6, zone="moonlit_graveyard", type="find", story="side",
  title=("小黑去哪儿了", "Where's Blackie?"), giver="gravekeeper_zhou", giverAt=Z("moonlit_graveyard", "npc", "level_1_entry", "moonlit_crypt_1/npc_1"), hook="q6_moonlit_crypt_1_npc_1",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "gravekeeper_zhou"}, Z("moonlit_graveyard", "npc", "level_1_entry", "moonlit_crypt_1/npc_1"), "His dog chased a skeleton's bone boomerang into the crypt."),
         ("nothing", {"type": "reach"}, Z("moonlit_graveyard", "fork", "branch"), "Empty kennel, only paw prints (a 'nothing' beat that points onward)."),
         ("story", {"type": "pickup", "item": "blackie"}, Z("moonlit_graveyard", "story", "dead_end", "moonlit_crypt_1/story_1"), "Blackie is chewing the boomerang, very proud."),
         ("quest_offer", {"type": "turn_in", "npc": "gravekeeper_zhou"}, Z("moonlit_graveyard", "npc", "level_1_entry"), "")],
  rewards=dict(G=5, items={"honey": 1}, L=15),
  words=["C148", "C408", "C409", "C410", "C414", "C871"],
  summary="Follow the paw prints into the Moonlit Crypt and bring the gravekeeper's dog Blackie home.")
q(id="q6_rattle_bones", realm=6, zone="moonlit_graveyard", type="slay", story="side",
  title=("吵闹的骷髅", "Too Much Rattling"), giver="gravekeeper_zhou", giverAt=Z("moonlit_graveyard", "npc", "level_1_entry", "moonlit_crypt_1/npc_1"), hook="q6_moonlit_crypt_1_npc_1",
  turnIn="giver", requires={"questClaimed": "q6_lost_dog"},
  steps=[("quest_offer", {"type": "talk", "npc": "gravekeeper_zhou"}, Z("moonlit_graveyard", "npc", "level_1_entry"), "Skeletons keep knocking over the flowers."),
         ("edge_battle", {"type": "kill", "enemy": "rattle_skeleton", "n": 8, "scope": {"zone": "moonlit_graveyard"}}, Z("moonlit_graveyard", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "gravekeeper_zhou"}, Z("moonlit_graveyard", "npc", "level_1_entry"), "")],
  rewards=dict(G=5, items={}, L=15),
  words=["C881", "C869", "C416", "C415", "C417"],
  summary="Scatter 8 rattle skeletons so the gravekeeper can replant the flowers.")
q(id="q6_knight_dad", realm=6, zone="moonlit_graveyard", type="rescue", story="main",
  title=("骑士爸爸", "Cure My Dad, the Knight"), giver="lingling", giverAt=Z("moonlit_graveyard", "npc", "level_2_entry", "moonlit_crypt_2/npc_1"), hook="q6_moonlit_crypt_2_npc_1",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "lingling"}, Z("moonlit_graveyard", "npc", "level_2_entry", "moonlit_crypt_2/npc_1"), "Her dad, the village knight, 'turned into a zombie' guarding the crypt."),
         ("story", {"type": "reach"}, Z("moonlit_graveyard", "story", "mid_level_2", "moonlit_crypt_2/story_2"), "General Mo refuses Madame Mist's plan (foreshadow)."),
         ("miniboss", {"type": "fight", "enemies": ["zombie_knight", "rattle_skeleton"]}, Z("moonlit_graveyard", "miniboss", "dead_end", "moonlit_crypt_2/deadend_1"), "Cured at 0 HP."),
         ("quest_offer", {"type": "turn_in", "npc": "lingling"}, Z("moonlit_graveyard", "npc", "level_2_entry", "moonlit_crypt_2/npc_2"), "Dad and daughter hug (he waits at npc_2).")],
  rewards=dict(G=0, items={}, gear=[(6, "shield", "fine")], L=30),
  words=["C273", "C862", "C847", "C874", "C872", "C885"],
  summary="Cure Lingling's dad, the Zombie Knight, in the lower crypt and bring father and daughter back together.")

# ---------------- Realm 7 Griffin Peaks (G=54) ----------------
q(id="q7_glacier_roses", realm=7, zone="windy_cliffs", type="fetch", story="side",
  title=("三朵冰川玫瑰", "Three Glacier Roses"), giver="granny_xue", giverAt=Z("windy_cliffs", "village", "outpost_1"), hook=None,
  turnIn="giver", requires={"bossDefeated": "windy_cliffs"},
  steps=[("quest_offer", {"type": "talk", "npc": "granny_xue"}, Z("windy_cliffs", "village", "outpost_1"), "(Jack's example.) Granny Xue's snow-tea needs 3 glacier roses that bloom only in snow."),
         ("item", {"type": "pickup", "item": "glacier_rose"}, Z("windy_cliffs", "chest", "dead_end"), "Rose 1 on a windy ledge."),
         ("portal", {"type": "reach"}, Z("windy_cliffs", "portal", "optional", "realm_7/portal_2"), "Cloud Caves (optional)."),
         ("item", {"type": "pickup", "item": "glacier_rose"}, Z("windy_cliffs", "story", "cloud_caves_dead_end", "cloud_caves_1/story_1"), "Rose 2 in an ice grotto."),
         ("miniboss", {"type": "fight", "enemies": ["cliff_golem", "harpy"]}, Z("windy_cliffs", "miniboss", "cloud_caves", "cloud_caves_1/miniboss_1"), "A golem is sitting on rose 3."),
         ("item", {"type": "pickup", "item": "glacier_rose"}, Z("windy_cliffs", "miniboss", "cloud_caves"), "Rose 3."),
         ("quest_offer", {"type": "turn_in", "npc": "granny_xue"}, Z("windy_cliffs", "village", "outpost_1"), "She teaches 雪球术 (or pays its 1,080-gold shop price if already owned).")],
  rewards=dict(G=0, items={}, L=25, spells=["snowball_volley"]),
  words=["C936", "C476", "C474", "C471", "C142", "C450"],
  summary="Collect 3 glacier roses from the snowy cliffs and the Cloud Caves; Granny Xue teaches you Snowball Volley.")
q(id="q7_lost_mapmaker", realm=7, zone="windy_cliffs", type="escort", story="side",
  title=("我迷路了", "The Lost Map-Maker"), giver="mapmaker_lu", giverAt=Z("windy_cliffs", "npc", "branch", "realm_7/npc_1"), hook="q7_realm_7_npc_1",
  turnIn={"npc": "mapmaker_lu", "zone": "windy_cliffs", "nodeKind": "town"}, requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "mapmaker_lu"}, Z("windy_cliffs", "npc", "branch", "realm_7/npc_1"), "A map-maker who is, embarrassingly, lost: 我迷路了!"),
         ("story", {"type": "reach"}, Z("windy_cliffs", "story", "fork"), "Read the signpost: 往左走 / 往右走 / 一直走 (choice)."),
         ("edge_battle", {"type": "escort", "npc": "mapmaker_lu", "to": {"zone": "windy_cliffs", "nodeKind": "town"}}, Z("windy_cliffs", "path", "npc_to_town"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "mapmaker_lu"}, Z("windy_cliffs", "town", "entry_town"), "He gives you a map with a ? on it (marks the Cloud Caves door).")],
  rewards=dict(G=4, items={"feather": 2}, L=15),
  words=["C908", "C907", "C453", "C457", "C458", "C456"],
  summary="Guide the lost map-maker back to Cloud Ridge by reading the cliff signposts.")
q(id="q7_harpy_socks", realm=7, zone="windy_cliffs", type="slay", story="side",
  title=("鹰身女妖", "Harpies on the Washing Line"), giver="laundry_auntie", giverAt=Z("windy_cliffs", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None, alsoOnBoard=True,
  steps=[("quest_offer", {"type": "talk", "npc": "laundry_auntie"}, Z("windy_cliffs", "town", "entry_town"), "Harpies keep stealing socks off the line."),
         ("edge_battle", {"type": "kill", "enemy": "harpy", "n": 8, "scope": {"realm": 7}}, Z("windy_cliffs", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "laundry_auntie"}, Z("windy_cliffs", "town", "entry_town"), "")],
  rewards=dict(G=4, items={"honey": 1}, L=15),
  words=["C428", "C429", "C430", "C431", "C441", "C442"],
  summary="Shoo away 8 sock-stealing harpies from Cloud Ridge's washing lines.")
q(id="q7_golem_sign", realm=7, zone="windy_cliffs", type="slay", story="side",
  title=("一直走的石头人", "The Golem Who Only Walks Straight"), giver="road_warden_he", giverAt=Z("windy_cliffs", "npc", "mid_zone", "realm_7/npc_2"), hook="q7_realm_7_npc_2",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "road_warden_he"}, Z("windy_cliffs", "npc", "mid_zone", "realm_7/npc_2"), "A cliff golem walked off with the crossroads signpost."),
         ("miniboss", {"type": "fight", "enemies": ["cliff_golem", "harpy", "harpy"]}, Z("windy_cliffs", "miniboss", "dead_end", "realm_7/miniboss_1"), ""),
         ("item", {"type": "pickup", "item": "signpost"}, Z("windy_cliffs", "miniboss", "dead_end"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "road_warden_he"}, Z("windy_cliffs", "npc", "mid_zone"), "")],
  rewards=dict(G=6, items={"honey": 1}, L=20),
  words=["C456", "C901", "C437", "C438", "C439", "C440"],
  summary="Stop the golem that keeps walking straight through houses and bring back the crossroads signpost.")
q(id="q7_griffin_feathers", realm=7, zone="griffin_summit", type="fetch", story="side",
  title=("狮鹫羽毛", "Shed Griffin Feathers"), giver="yezi", giverAt=Z("griffin_summit", "npc", "level_1", "griffin_spire_1/npc_1"), hook="q7_griffin_spire_1_npc_1",
  turnIn="giver", requires={"bossDefeated": "windy_cliffs"},
  steps=[("quest_offer", {"type": "talk", "npc": "yezi"}, Z("griffin_summit", "npc", "level_1", "griffin_spire_1/npc_1"), "Yezi needs shed feathers (never plucked!) for elf arrows."),
         ("item", {"type": "pickup", "item": "griffin_feather", "n": 3}, Z("griffin_summit", "chest", "levels_1_2_dead_ends"), "3 feather nests on the Spire's side branches."),
         ("quest_offer", {"type": "turn_in", "npc": "yezi"}, Z("griffin_summit", "npc", "level_1"), "")],
  rewards=dict(G=4, items={"honey": 1}, L=15),
  words=["C941", "C466", "C482", "C477", "C924"],
  summary="Pick up 3 shed griffin feathers from the Spire's nests for Yezi's elf arrows.")
q(id="q7_griffin_chick", realm=7, zone="griffin_summit", type="rescue", story="side",
  title=("小狮鹫回家", "A Chick Far From the Nest"), giver="griffin_chick", giverAt=Z("griffin_summit", "npc", "level_2", "griffin_spire_2/npc_1"), hook="q7_griffin_spire_2_npc_1",
  turnIn={"npc": "griffin_mother", "zone": "griffin_summit", "nodeKind": "npc"}, requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "griffin_chick"}, Z("griffin_summit", "npc", "level_2", "griffin_spire_2/npc_1"), "A fluffy chick blown down by the storm (too young to be bewitched)."),
         ("miniboss", {"type": "fight", "enemies": ["griffin", "harpy"]}, Z("griffin_summit", "miniboss", "level_2", "griffin_spire_2/miniboss_1"), "Harpies want the chick."),
         ("edge_battle", {"type": "escort", "npc": "griffin_chick", "to": {"zone": "griffin_summit", "nodeKind": "npc", "ref": "griffin_spire_3/npc_1"}}, Z("griffin_summit", "stairs", "level_2_to_3"), "Carry it upstairs."),
         ("quest_offer", {"type": "turn_in", "npc": "griffin_mother"}, Z("griffin_summit", "npc", "level_3", "griffin_spire_3/npc_1"), "Its mother: 'Free our king.'")],
  rewards=dict(G=9, items={"manatea": 1}, L=25),
  words=["C912", "C911", "C915", "C914", "C913", "C468"],
  summary="Save a griffin chick from harpies and carry it up the Spire to its mother below the King's roost.")
q(id="q7_forecast", realm=7, zone="griffin_summit", type="deliver", story="side",
  title=("天气预报", "Tomorrow's Weather"), giver="weather_sage", giverAt=Z("windy_cliffs", "town", "entry_town"), hook=None,
  turnIn="giver", requires={"bossDefeated": "windy_cliffs"},
  steps=[("quest_offer", {"type": "talk", "npc": "weather_sage"}, Z("windy_cliffs", "town", "entry_town"), "The weather sage's forecasts must reach the outposts before the storm."),
         ("quest_offer", {"type": "deliver", "item": "forecast", "to": "outpost_keeper_7a"}, Z("windy_cliffs", "village", "outpost_1"), ""),
         ("quest_offer", {"type": "deliver", "item": "forecast", "to": "outpost_keeper_7b"}, Z("windy_cliffs", "village", "outpost_2"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "weather_sage"}, Z("windy_cliffs", "town", "entry_town"), "")],
  rewards=dict(G=3, items={"feather": 1}, L=15),
  words=["C939", "C940", "C470", "C473", "C478", "C932"],
  summary="Run the weather sage's storm forecast out to both Cloud Ridge outposts.")

# ---------------- Realm 8 Ogre Colosseum (G=63) ----------------
q(id="q8_fire_demon", realm=8, zone="training_pits", type="slay", story="side",
  title=("火魔烧庄稼", "The Fire Demon in the Wheat"), giver="farmer_wang", giverAt=Z("training_pits", "village", "outpost_1"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "farmer_wang"}, Z("training_pits", "village", "outpost_1"), "(Jack's example.) A dancing fire demon is burning the crops."),
         ("story", {"type": "reach"}, Z("training_pits", "story", "mid_zone", "realm_8/story_1"), "Smoky (never burning-people) fields; cows hiding behind a barn."),
         ("miniboss", {"type": "fight", "enemies": ["fire_elemental", "arena_troll", "arena_troll"]}, Z("training_pits", "miniboss", "dead_end", "realm_8/miniboss_1"), "Named variant 'Blaze' (fire_elemental); trolls fan the flames."),
         ("quest_offer", {"type": "turn_in", "npc": "farmer_wang"}, Z("training_pits", "village", "outpost_1"), "A rain dance with the farmers.")],
  rewards=dict(G=0, items={}, gear=[(8, "shield", "fine")], L=25),
  words=["C497", "C946", "C489", "C964", "C508"],
  summary="Defeat Blaze, the dancing fire demon burning Farmer Wang's crops, and his troll helpers.")
q(id="q8_lost_ball", realm=8, zone="training_pits", type="find", story="side",
  title=("足球在哪儿", "Ball Over the Wall"), giver="troll_kid_dudu", giverAt=Z("training_pits", "npc", "branch", "realm_8/npc_1"), hook="q8_realm_8_npc_1",
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "troll_kid_dudu"}, Z("training_pits", "npc", "branch", "realm_8/npc_1"), "A young troll kicked his ball into the Beast Pens."),
         ("portal", {"type": "reach"}, Z("training_pits", "portal", "optional", "realm_8/portal_2"), "Beast Pens (optional)."),
         ("item", {"type": "pickup", "item": "soccer_ball"}, Z("training_pits", "story", "beast_pens_dead_end", "beast_pens_1/story_1"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "troll_kid_dudu"}, Z("training_pits", "npc", "branch"), "He challenges you to a penalty kick (choice).")],
  rewards=dict(G=4, items={"honey": 1}, L=15),
  words=["C490", "C492", "C942", "C946", "C508"],
  summary="Fetch a young troll's soccer ball from the Beast Pens and take his penalty-kick challenge.")
q(id="q8_training", realm=8, zone="training_pits", type="slay", story="side",
  title=("训练", "Coach Niu's Drills"), giver="coach_niu", giverAt=Z("training_pits", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None, alsoOnBoard=True,
  steps=[("quest_offer", {"type": "talk", "npc": "coach_niu"}, Z("training_pits", "town", "entry_town"), "The arena coach: 'Beat 8 trolls and you enter the tournament as a seed.'"),
         ("edge_battle", {"type": "kill", "enemy": "arena_troll", "n": 8, "scope": {"realm": 8}}, Z("training_pits", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "coach_niu"}, Z("training_pits", "town", "entry_town"), "")],
  rewards=dict(G=4, items={"honey": 1}, L=15),
  words=["C952", "C953", "C951", "C964", "C965", "C955"],
  summary="Win 8 fights against arena trolls to finish Coach Niu's drills.")
q(id="q8_bronze_medals", realm=8, zone="grand_colosseum", type="fetch", story="side",
  title=("铜奖牌", "Medals for the Museum"), giver="curator_bao", giverAt=Z("grand_colosseum", "npc", "level_2", "undercroft_2/npc_1"), hook="q8_undercroft_2_npc_1",
  turnIn="giver", requires={"bossDefeated": "training_pits"},
  steps=[("quest_offer", {"type": "talk", "npc": "curator_bao"}, Z("grand_colosseum", "npc", "level_2", "undercroft_2/npc_1"), "Gladiators wear stolen museum medals on their bottle-cap belts."),
         ("edge_battle", {"type": "collect", "item": "bronze_medal", "n": 5, "dropFrom": ["ogre_gladiator"], "dropChance": 0.35}, Z("grand_colosseum", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "curator_bao"}, Z("grand_colosseum", "npc", "level_2"), "")],
  rewards=dict(G=6, items={}, L=15),
  words=["C956", "C957", "C961", "C962", "C963"],
  summary="Win back 5 bronze medals from ogre gladiators for the Colosseum's little museum.")
q(id="q8_fan_letters", realm=8, zone="grand_colosseum", type="deliver", story="side",
  title=("球迷的信", "Fan Mail for Dachui"), giver="fan_xiaoli", giverAt=Z("training_pits", "village", "outpost_2"), hook=None,
  turnIn="giver", requires={"bossDefeated": "training_pits"},
  steps=[("quest_offer", {"type": "talk", "npc": "fan_xiaoli"}, Z("training_pits", "village", "outpost_2"), "The fan club's letters for the champion."),
         ("portal", {"type": "reach"}, Z("grand_colosseum", "portal", "overworld", "realm_8/portal_1"), ""),
         ("quest_offer", {"type": "deliver", "item": "fan_letters", "to": "dachui_manager"}, Z("grand_colosseum", "npc", "level_3", "undercroft_3/npc_1"), "His manager takes them backstage."),
         ("quest_offer", {"type": "turn_in", "npc": "fan_xiaoli"}, Z("training_pits", "village", "outpost_2"), "真的吗? He read them?!")],
  rewards=dict(G=4, items={"feather": 1}, L=15),
  words=["C975", "C974", "C517", "C513", "C534"],
  summary="Deliver the fan club's letters to the Ogre Champion's manager under the Colosseum.")
q(id="q8_singer_escort", realm=8, zone="grand_colosseum", type="escort", story="main",
  title=("开幕歌手", "The Opening Song"), giver="singer_meimei", giverAt=Z("grand_colosseum", "npc", "level_1", "undercroft_1/npc_2"), hook="q8_undercroft_1_npc_2",
  turnIn="auto", requires={"bossDefeated": "training_pits"},
  steps=[("quest_offer", {"type": "talk", "npc": "singer_meimei"}, Z("grand_colosseum", "npc", "level_1", "undercroft_1/npc_2"), "The anthem singer is lost under the stands; the final can't start without her."),
         ("miniboss", {"type": "fight", "enemies": ["ogre_gladiator", "fire_elemental"]}, Z("grand_colosseum", "miniboss", "level_2", "undercroft_2/miniboss_1"), "Pipi's hired hecklers."),
         ("edge_battle", {"type": "escort", "npc": "singer_meimei", "to": {"zone": "grand_colosseum", "nodeKind": "story", "ref": "undercroft_3/story_1"}}, Z("grand_colosseum", "stairs", "level_1_to_3"), ""),
         ("story", {"type": "reach"}, Z("grand_colosseum", "story", "level_3_boss_approach", "undercroft_3/story_1"), "She sings; the crowd cheers 加油! (auto-complete).")],
  rewards=dict(G=6, items={}, L=25),
  words=["C496", "C972", "C973", "C966", "C967", "C523"],
  summary="Lead the anthem singer through the Undercroft past Pipi's hecklers so the final can begin.")
q(id="q8_caged_beasts", realm=8, zone="training_pits", type="rescue", story="side",
  title=("放动物出来", "Open the Beast Pens"), giver="vet_ji", giverAt=Z("training_pits", "village", "outpost_2"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "vet_ji"}, Z("training_pits", "village", "outpost_2"), "Animals kept for 'monster shows' need freeing. Vet Ji works at Arena Town outpost 2 (realm_8/town_3), right next to the Beast Pens door portal_2."),
         ("portal", {"type": "reach"}, Z("training_pits", "portal", "optional", "realm_8/portal_2"), "Beast Pens (optional)."),
         ("miniboss", {"type": "fight", "enemies": ["arena_troll", "arena_troll", "ogre_gladiator"]}, Z("training_pits", "deadend", "beast_pens_level_1", "beast_pens_1/deadend_3"), "The pen keepers, at the dead end past the inn_1 rest stop (quest-gated fight, cond questActive q8_caged_beasts). v3.9: beast_pens_1/miniboss_1 is a campfire inn, so the fight moved here."),
         ("story", {"type": "reach"}, Z("training_pits", "deadend", "beast_pens_level_2", "beast_pens_2/deadend_1"), "Open 3 cages: an elephant, a tiger and a horse run free."),
         ("quest_offer", {"type": "turn_in", "npc": "vet_ji"}, Z("training_pits", "village", "outpost_2"), "")],
  rewards=dict(G=6, items={}, L=25),
  words=["C657", "C156", "C151", "C146", "C495"],
  summary="Beat the pen keepers in the Beast Pens and set an elephant, a tiger and a horse free.")

# ---------------- Realm 9 Demon King's Castle (G=72) ----------------
q(id="q9_pact_elves", realm=9, zone="demon_king_s_gate", type="find", story="main",
  title=("精灵的宝石", "The Elves' Moonstone"), giver="yezi", giverAt=Z("demon_king_s_gate", "village", "lantern_outpost_1"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "yezi"}, Z("demon_king_s_gate", "village", "lantern_outpost_1"), "The elves join only if their stolen moonstone comes home. Opinion choices: 我同意 / 我觉得..."),
         ("portal", {"type": "reach"}, Z("demon_king_s_gate", "portal", "optional", "realm_9/portal_2"), "Shadow Vault (optional)."),
         ("miniboss", {"type": "fight", "enemies": ["gargoyle", "imp", "imp"]}, Z("demon_king_s_gate", "miniboss", "vault_level_2", "shadow_vault_2/miniboss_1"), ""),
         ("story", {"type": "pickup", "item": "moonstone"}, Z("demon_king_s_gate", "story", "vault_level_2", "shadow_vault_2/story_1"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "yezi"}, Z("demon_king_s_gate", "village", "lantern_outpost_1"), "The elf banner goes up in camp.")],
  rewards=dict(G=5, items={"bighoney": 1}, L=30, flags=["pact_elves"]),
  words=["C1009", "C550", "C555", "C557", "C546"],
  summary="Win back the elves' moonstone from the Shadow Vault so the elves join the alliance.")
q(id="q9_pact_dwarves", realm=9, zone="demon_king_s_gate", type="fetch", story="main",
  title=("矮人的水晶", "Shadow Crystals for the Forge"), giver="uncle_shi", giverAt=Z("demon_king_s_gate", "village", "lantern_outpost_2"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "uncle_shi"}, Z("demon_king_s_gate", "village", "lantern_outpost_2"), "The dwarves need shadow crystals to rebuild the Harmony Bell's frame."),
         ("edge_battle", {"type": "collect", "item": "shadow_crystal", "n": 5, "dropFrom": ["imp"], "dropChance": 0.35}, Z("demon_king_s_gate", "path", "any"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "uncle_shi"}, Z("demon_king_s_gate", "village", "lantern_outpost_2"), "只要……就…… line.")],
  rewards=dict(G=4, items={"honey": 1}, L=20, flags=["pact_dwarves"]),
  words=["C997", "C1012", "C1014", "C1020", "C1013"],
  summary="Collect 5 shadow crystals from imps so Uncle Shi's dwarves can rebuild the Harmony Bell's frame.")
q(id="q9_pact_beastfolk", realm=9, zone="throne_hall", type="slay", story="main",
  title=("兽人的战斗", "Side by Side with Dachui"), giver="dachui", giverAt=Z("demon_king_s_gate", "village", "lantern_outpost_3"), hook=None,
  turnIn="giver", requires={"bossDefeated": "demon_king_s_gate"},
  steps=[("quest_offer", {"type": "talk", "npc": "dachui"}, Z("demon_king_s_gate", "village", "lantern_outpost_3"), "The beastfolk champion wants proof you fight for everyone."),
         ("edge_battle", {"type": "kill", "enemy": "demon_knight", "n": 6, "scope": {"zone": "throne_hall"}}, Z("throne_hall", "path", "levels_3_4"), "Dachui cheers from the sidelines (no combat change)."),
         ("story", {"type": "reach"}, Z("throne_hall", "story", "level_3", "demon_castle_3/story_1"), "Dachui: 不但……而且……"),
         ("quest_offer", {"type": "turn_in", "npc": "dachui"}, Z("demon_king_s_gate", "village", "lantern_outpost_3"), "")],
  rewards=dict(G=4, items={"honey": 1}, L=20, flags=["pact_beastfolk"]),
  words=["C583", "C580", "C540", "C561", "C1021", "C1022"],
  summary="Defeat 6 demon knights in the Throne Hall levels to earn the beastfolk's trust.")
q(id="q9_dragonlings", realm=9, zone="demon_king_s_gate", type="rescue", story="main",
  title=("救小龙们", "The Caged Dragonlings"), giver="wind_dragon", giverAt=Z("demon_king_s_gate", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None,
  steps=[("quest_offer", {"type": "talk", "npc": "wind_dragon"}, Z("demon_king_s_gate", "town", "entry_town"), "Uncle Wind: three dragonlings are caged in the castle."),
         ("story", {"type": "talk", "npc": "dragonling_1"}, Z("demon_king_s_gate", "npc", "castle_level_1", "demon_castle_1/npc_1"), ""),
         ("story", {"type": "talk", "npc": "dragonling_2"}, Z("demon_king_s_gate", "npc", "castle_level_1_deep", "demon_castle_1/npc_2"), ""),
         ("miniboss", {"type": "fight", "enemies": ["gargoyle", "imp", "imp"]}, Z("demon_king_s_gate", "miniboss", "castle_level_1", "demon_castle_1/miniboss_1"), "Cage guards."),
         ("story", {"type": "talk", "npc": "dragonling_3"}, Z("demon_king_s_gate", "npc", "castle_level_2", "demon_castle_2/npc_1"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "wind_dragon"}, Z("demon_king_s_gate", "town", "entry_town"), "")],
  rewards=dict(G=6, items={"bighoney": 1}, L=30, flags=["pact_dragons"]),
  words=["C296", "C999", "C1003", "C549", "C548"],
  summary="Free three caged dragonlings in the castle's first levels so the dragons join the alliance.")
q(id="q9_second_wind", realm=9, zone="demon_king_s_gate", type="fetch", story="main",
  title=("白奶奶最后一课", "Granny Bai's Last Lesson"), giver="granny_bai", giverAt=Z("demon_king_s_gate", "town", "entry_town"), hook=None,
  turnIn="giver", requires={"any": [{"flag": "pact_elves"}, {"flag": "pact_dwarves"}, {"flag": "pact_dragons"}]},
  steps=[("quest_offer", {"type": "talk", "npc": "granny_bai"}, Z("demon_king_s_gate", "town", "entry_town"), "'A hero is someone who gets up again.'"),
         ("treasure", {"type": "pickup", "item": "old_hero_badge"}, Z("demon_king_s_gate", "chest", "castle_level_2_dead_end", "demon_castle_2"), "Her old badge, lost 50 years ago (quest item before the chest)."),
         ("quest_offer", {"type": "words", "pool": "L9.1", "n": 12, "countFrom": "accept"}, Z("demon_king_s_gate", "town", "entry_town"), "Get 12 Gate words Ready."),
         ("quest_offer", {"type": "turn_in", "npc": "granny_bai"}, Z("demon_king_s_gate", "town", "entry_town"), "She teaches 再起 Second Wind (spec: Castle quest).")],
  rewards=dict(G=3, items={}, L=30, skills=["second_wind"]),
  words=["C565", "C564", "C561", "C1002", "C554"],
  summary="Recover Granny Bai's old hero badge and learn 12 Gate words; she teaches you Second Wind.")
q(id="q9_pipi_surrender", realm=9, zone="throne_hall", type="escort", story="main",
  title=("皮皮投降", "Pipi Gives Up"), giver="pipi", giverAt=Z("demon_king_s_gate", "npc", "castle_level_2", "demon_castle_2/npc_2"), hook="q9_demon_castle_2_npc_2",
  turnIn={"npc": "granny_bai", "zone": "demon_king_s_gate", "nodeKind": "town"}, requires={"bossDefeated": "demon_king_s_gate"},
  steps=[("quest_offer", {"type": "talk", "npc": "pipi"}, Z("demon_king_s_gate", "npc", "castle_level_2", "demon_castle_2/npc_2"), "Abandoned after the curse breaks: 我投降!"),
         ("edge_battle", {"type": "escort", "npc": "pipi", "to": {"zone": "demon_king_s_gate", "nodeKind": "town"}}, Z("demon_king_s_gate", "path", "castle_to_camp"), "Feather and inn warp allowed; Pipi jokes along the way."),
         ("quest_offer", {"type": "turn_in", "npc": "granny_bai"}, Z("demon_king_s_gate", "town", "entry_town"), "Pipi trades a secret Throne Hall key for a second chance.")],
  rewards=dict(G=4, items={}, L=20, flags=["throne_shortcut"]),
  words=["C1028", "C1027", "C1046", "C1047", "C568"],
  summary="Bring the abandoned imp Pipi safely back to Lantern Light Camp, where he trades a secret key for a second chance.")
q(id="q9_lanterns", realm=9, zone="demon_king_s_gate", type="deliver", story="side",
  title=("灯火", "Light Every Lantern"), giver="lantern_keeper_deng", giverAt=Z("demon_king_s_gate", "town", "entry_town"), hook=None,
  turnIn="giver", requires=None, alsoOnBoard=True,
  steps=[("quest_offer", {"type": "talk", "npc": "lantern_keeper_deng"}, Z("demon_king_s_gate", "town", "entry_town"), "The camp's lanterns keep the fog out."),
         ("quest_offer", {"type": "deliver", "item": "lantern_oil", "to": "outpost_keeper_9a"}, Z("demon_king_s_gate", "village", "lantern_outpost_1"), ""),
         ("quest_offer", {"type": "deliver", "item": "lantern_oil", "to": "outpost_keeper_9b"}, Z("demon_king_s_gate", "village", "lantern_outpost_2"), ""),
         ("quest_offer", {"type": "deliver", "item": "lantern_oil", "to": "outpost_keeper_9c"}, Z("demon_king_s_gate", "village", "lantern_outpost_3"), ""),
         ("quest_offer", {"type": "turn_in", "npc": "lantern_keeper_deng"}, Z("demon_king_s_gate", "town", "entry_town"), "")],
  rewards=dict(G=4, items={"feather": 1}, L=15),
  words=["C1007", "C1005", "C552", "C553", "C1006"],
  summary="Carry lantern oil to Lantern Light Camp's three outposts to keep the Demon King's fog away.")
