"""Builds world_sim.py = spells_sim.py (v3.7 campaign) + the v3.8 realm-graph zone loop (world_loop.py.txt). world=None reproduces v3.7."""
src = open('/workspace/desy/build/spells_sim.py').read()
start = src.index("        for loc in range(C.LOCS[t]):")
end = src.index("            R['loc_min'].append(tq_minutes() - m0)\n") + len("            R['loc_min'].append(tq_minutes() - m0)\n")
old = src[start:end]
loop = "        for loc in range(C.LOCS[t]):\n            if world: world_zone(loc); continue\n" + old.split("\n", 1)[1]
def rep(s, a, b):
    assert a in s, a[:60]; return s.replace(a, b)
loop = rep(loop, "            R['patrols'] += pat\n", "            R['patrols'] += pat; R['path_battles'] += 8\n")
loop = rep(loop, "            pat = 0\n            while C.pool_score(L, local, 'items') < thresh", "            pat = 0; R['ready_gate'].append(C.pool_score(L, local, 'items'))\n            while C.pool_score(L, local, 'items') < thresh")
loop = rep(loop, "            between(before_boss=True); resume = False\n", "            between(before_boss=True); resume = False; R['ready_boss'].append(C.pool_score(L, local, 'items'))\n")
src = src[:start] + loop + src[end:]
src = rep(src, "boss_mp_start=[], boss_hp_lost=[], boss_casts=[], tea_gold=0)", "boss_mp_start=[], boss_hp_lost=[], boss_casts=[], tea_gold=0,\n                 path_battles=0, side_battles=0, back_battles=0, ready_gate=[], ready_boss=[], hops=0, feathers=0, inn_trips=0, inn_walk_hops=0, gold_side=0, minis=0, items_found=0)")
src = rep(src, "            if not won: defeat()\n            else: shop()\n", "            if not won: defeat()\n            elif not (world and opt.get('village_shop', True)): shop()\n")
src = rep(src, "    tq_minutes = lambda: (stats['q']*C.SEC_PER_Q", "    tq_minutes = lambda: (stats.get('walk_sec', 0) + stats['q']*C.SEC_PER_Q")
src = rep(src, "    rng = random.Random(seed)\n", "    rng = random.Random(seed)\n    world = opt.get('world')     # None = the v3.7 loop; 'beeline' / 'explore' = v3.8 realm-graph traversal\n")
src = rep(src, "tea=0, bigtea=0)", "tea=0, bigtea=0, feather=1)")
src = rep(src, "        def fight(kind, local, rslots, loc, resume=False, elite=False):", open('/workspace/desy/build/world/world_loop.py.txt').read() + "        def fight(kind, local, rslots, loc, resume=False, elite=False):")
src = src.replace('"""v3.3 campaign simulator', '"""v3.8 world-graph campaign simulator (GENERATED by build_world_sim.py): spells_sim.py (v3.7) + a realm-graph zone loop (opt world=beeline/explore); world=None reproduces v3.7.\nOriginal docstring: v3.3 campaign simulator', 1)
src = rep(src, "import spells_data_v3_3 as D33\n", "import spells_data_v3_3 as D33\nimport heapq\nsys.path.insert(0, '/workspace/desy/build/world')\nimport world_graph as WG\n")
open('/workspace/desy/build/world/world_sim.py', 'w').write(src); print('world_sim.py built')
